# version: '3.8'

services:
  embedding_service:
    build:
      context: ./embedding_service
      dockerfile: Dockerfile
    container_name: embedding_service
    env_file:
      - ./.env # Uses root .env
    ports:
      # Host port (left of :) can use var from .env or be hardcoded for simplicity on Droplet
      # Container port (right of :) must match what Uvicorn uses (EMBEDDING_SERVICE_PORT from .env)
      - "${EMBEDDING_SERVICE_PORT_HOST:-8001}:8001"
    volumes:
      - ./embedding_model_cache:/root/.cache
      # - ./embedding_service:/app # UNCOMMENT FOR LOCAL DEV HOT RELOAD ONLY
    restart: unless-stopped
    networks:
      - app_network

  rag_api_service:
    build:
      context: ./rag_api_service
      dockerfile: Dockerfile
    container_name: rag_api_service
    env_file:
      - ./.env # Uses root .env
    ports:
      - "${RAG_API_PORT_HOST:-8002}:8002"
    volumes:
      # - ./rag_api_service:/app # UNCOMMENT FOR LOCAL DEV HOT RELOAD ONLY
    depends_on:
      - embedding_service
      - ollama
    restart: unless-stopped
    networks:
      - app_network

  ollama:
    # ... (as before) ...
    volumes:
      - ./ollama_data:/root/.ollama
    # ...

  frontend_nginx:
    build:
      context: ./search_ui
      dockerfile: Dockerfile
      args: # Pass build-time ARGs from the root .env file to the Dockerfile
        VITE_MSAL_REDIRECT_URI: ${VITE_MSAL_REDIRECT_URI} # Reads from root .env
        VITE_RAG_API_URL: ${VITE_RAG_API_URL}             # Reads from root .env
    container_name: frontend_nginx
    ports:
      - "${FRONTEND_PORT_HOST:-5173}:80" # Host port : Nginx container port
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ollama_data:
  embedding_model_cache: