-- Sample document chunks for testing hybrid search functionality
-- These chunks represent actual content from the documents with dummy embeddings
-- Note: In production, embeddings would be generated by the embedding service

-- Generate dummy embeddings (1024 dimensions filled with small random values)
-- This is a simplified approach for seed data - real embeddings would be generated by the embedding service

INSERT INTO document_chunks (
    document_id,
    chunk_index,
    content,
    embedding
) VALUES 
-- Chunks for document 1 (Small Business CGT Concessions)
(
    1,
    0,
    'Small business capital gains tax (CGT) concessions provide significant tax relief for eligible small businesses when disposing of active assets or business interests. The main concessions include the 15-year exemption, 50% active asset reduction, retirement exemption, and rollover relief. These concessions can substantially reduce or eliminate CGT liability for qualifying small business owners.',
    array_fill(0.01, ARRAY[1024])::vector
),
(
    1,
    1,
    'To access small business CGT concessions, businesses must satisfy the basic conditions including the $6 million net asset value test, active asset test (80% for companies and trusts, 90% for individuals), and carrying on a business test. The aggregated turnover threshold is $2 million for most concessions, though some have higher thresholds.',
    array_fill(0.02, ARRAY[1024])::vector
),
(
    1,
    2,
    'The small business 15-year exemption allows a complete exemption from CGT if you continuously owned the CGT asset for at least 15 years and you are aged 55 or over and retiring, or permanently incapacitated. This exemption applies to assets continuously owned since before 1 January 1999 for individuals, or since incorporation for companies.',
    array_fill(0.03, ARRAY[1024])::vector
),

-- Chunks for document 2 (Restraint of Trade)
(
    2,
    0,
    'Restraint of trade clauses in executive employment contracts must be reasonable in scope, duration, and geographical limitation to be enforceable under Australian law. Courts will not enforce restraints that go beyond what is necessary to protect the employer''s legitimate business interests, such as confidential information, customer relationships, or trade secrets.',
    array_fill(0.04, ARRAY[1024])::vector
),
(
    2,
    1,
    'The enforceability of restraint of trade provisions depends on several factors: the seniority of the employee, access to confidential information, customer contact, competition with the former employer, and whether the restraint is supported by adequate consideration. Executive positions typically justify broader restraints due to their access to strategic information.',
    array_fill(0.05, ARRAY[1024])::vector
),
(
    2,
    2,
    'Geographical limitations in restraint clauses must correspond to the employer''s actual market presence. A worldwide restraint may be justified for multinational executives, while local restraints are more appropriate for regional roles. Time limitations typically range from 6 months to 2 years, with longer periods requiring stronger justification.',
    array_fill(0.06, ARRAY[1024])::vector
),

-- Chunks for document 3 (Directors Duties)
(
    3,
    0,
    'Directors of Australian corporations owe statutory duties under sections 180-184 of the Corporations Act 2001. These include the duty to exercise care and diligence (s180), act in good faith in the best interests of the corporation (s181), not to improperly use position (s182), and not to improperly use information (s183).',
    array_fill(0.07, ARRAY[1024])::vector
),
(
    3,
    1,
    'The business judgment rule in section 180(2) provides protection for directors who make business decisions in good faith, for a proper purpose, without material personal interest, inform themselves appropriately, and rationally believe the decision is in the best interests of the corporation. This rule recognizes that business involves risk and uncertainty.',
    array_fill(0.08, ARRAY[1024])::vector
),
(
    3,
    2,
    'Fiduciary duties require directors to act in the best interests of the corporation as a whole, avoid conflicts of interest, and not to profit from their position without proper authorization. These duties exist alongside statutory obligations and can result in both civil and criminal liability for breaches.',
    array_fill(0.09, ARRAY[1024])::vector
),

-- Chunks for document 4 (Mining Safety WA)
(
    4,
    0,
    'Western Australian mining operations must comply with the Work Health and Safety Act 2020 and Mining Regulations. Key requirements include safety management systems, risk assessments, worker consultation, incident reporting, and regular safety audits. The Department of Mines, Industry Regulation and Safety (DMIRS) enforces these requirements.',
    array_fill(0.10, ARRAY[1024])::vector
),
(
    4,
    1,
    'Mining safety compliance requires comprehensive risk management including hazard identification, risk assessment, and implementation of control measures. Priority hazards in WA mining include falls from height, vehicle interactions, explosions, inrush/instability, and exposure to hazardous substances. Regular safety training and competency assessments are mandatory.',
    array_fill(0.11, ARRAY[1024])::vector
),
(
    4,
    2,
    'Reporting obligations for mining operations include immediate notification of serious incidents, regular safety performance reporting, and annual compliance certificates. Penalties for non-compliance can include substantial fines, prosecution of company officers, and suspension of mining operations. DMIRS conducts regular inspections and investigations.',
    array_fill(0.12, ARRAY[1024])::vector
),

-- Chunks for document 5 (GST Input Tax Credits)
(
    5,
    0,
    'Professional service providers can claim GST input tax credits for business-related purchases, provided they are registered for GST and the acquisitions are for a creditable purpose. Input tax credits are available for office expenses, professional development, business equipment, and other costs directly related to making taxable supplies.',
    array_fill(0.13, ARRAY[1024])::vector
),
(
    5,
    1,
    'Mixed-use assets require apportionment between business and private use for GST input tax credit purposes. Professional service providers must maintain detailed records to substantiate the business portion of expenses. Common mixed-use items include vehicles, mobile phones, home office expenses, and professional subscriptions.',
    array_fill(0.14, ARRAY[1024])::vector
),
(
    5,
    2,
    'The creditable purpose test requires that acquisitions be made for the purpose of making taxable supplies. Input tax credits are not available for private expenses, entertainment (subject to limited exceptions), or acquisitions related to input taxed supplies. Professional service providers must carefully categorize expenses to ensure compliance.',
    array_fill(0.15, ARRAY[1024])::vector
),

-- Chunks for document 6 (Essential Facilities Doctrine)
(
    6,
    0,
    'The essential facilities doctrine under Australian competition law provides that a business with control over an essential facility cannot refuse access to competitors without legitimate business justification. This doctrine applies where the facility is essential for competition, controlled by a potential competitor, and practically impossible to duplicate.',
    array_fill(0.16, ARRAY[1024])::vector
),
(
    6,
    1,
    'Essential facilities doctrine cases in Australia have involved telecommunications networks, port facilities, payment systems, and exclusive dealing arrangements. The High Court in Melway Publishing v Robert Hicks Pty Ltd established that mere ownership of a facility does not create an obligation to provide access to competitors.',
    array_fill(0.17, ARRAY[1024])::vector
),
(
    6,
    2,
    'ACCC enforcement of essential facilities principles considers market definition, barriers to entry, competitive effects, and potential efficiency justifications. The doctrine balances the property rights of facility owners against the competitive process. Recent cases have focused on digital platforms and data access issues.',
    array_fill(0.18, ARRAY[1024])::vector
); 